export const ROLES = ["admin", "doctor", "nurse", "receptionist", "hr", "patient", "lab_technician", "pharmacist"] as const;
export type Role = (typeof ROLES)[number];
export const ROLE_LABELS: Record<Role, string> = { admin: "Admin", doctor: "Doctor", nurse: "Nurse", receptionist: "Receptionist", hr: "HR", patient: "Patient", lab_technician: "Lab Technician", pharmacist: "Pharmacist" };
export type Permission = "dashboard:read" | "patients:read" | "patients:write" | "appointments:read" | "appointments:write" | "clinical:read" | "clinical:write" | "clinical:finalize" | "prescriptions:write" | "lab-requests:write" | "admissions:write" | "discharge:write" | "surgery:write" | "vitals:write" | "medication-administration:write" | "nursing-notes:write" | "handover:write" | "laboratory:read" | "laboratory:write" | "lab-results:write" | "lab-reports:publish" | "pharmacy:read" | "pharmacy:write" | "dispensing:write" | "stock:write" | "blood-bank:write" | "employees:read" | "employees:write" | "attendance:write" | "leave:approve" | "payroll:write" | "beds:read" | "beds:write" | "emergency:write" | "ambulance:write" | "billing:read" | "billing:write" | "payments:write" | "inventory:read" | "inventory:write" | "users:read" | "users:write" | "reports:read" | "settings:write" | "patient-portal:read";
const rolePermissions: Record<Role, Permission[] | ["*"]> = { admin: ["*"], doctor: ["dashboard:read", "patients:read", "appointments:read", "appointments:write", "clinical:read", "clinical:write", "clinical:finalize", "prescriptions:write", "lab-requests:write", "admissions:write", "discharge:write", "surgery:write", "laboratory:read", "reports:read"], nurse: ["dashboard:read", "patients:read", "appointments:read", "clinical:read", "vitals:write", "medication-administration:write", "nursing-notes:write", "handover:write"], receptionist: ["dashboard:read", "patients:read", "patients:write", "appointments:read", "appointments:write", "admissions:write", "billing:read", "billing:write", "payments:write", "reports:read"], hr: ["dashboard:read", "employees:read", "employees:write", "attendance:write", "leave:approve", "payroll:write", "beds:read", "beds:write", "emergency:write", "ambulance:write", "reports:read", "users:read"], patient: ["patient-portal:read"], lab_technician: ["dashboard:read", "patients:read", "laboratory:read", "laboratory:write", "lab-results:write", "lab-reports:publish", "inventory:read"], pharmacist: ["dashboard:read", "patients:read", "pharmacy:read", "pharmacy:write", "dispensing:write", "stock:write", "inventory:read", "inventory:write"] };
export function hasPermission(role: Role, permission: Permission, overrides: Permission[] = []) { const permissions: readonly (Permission | "*")[] = rolePermissions[role]; return permissions.includes("*") || permissions.includes(permission) || overrides.includes(permission); }

export type GranularPermission = "patient.view" | "patient.create" | "patient.update" | "appointment.view" | "appointment.create" | "appointment.update" | "appointment.cancel" | "clinical.view" | "clinical.write" | "prescription.create" | "prescription.view" | "lab.order.create" | "lab.result.write" | "lab.report.publish" | "billing.create" | "billing.payment.collect" | "billing.refund.request" | "bed.manage" | "employee.manage" | "leave.approve" | "pharmacy.dispense" | "pharmacy.inventory.manage" | "cms.manage" | "user.manage" | "audit.view";
const granularMap: Record<GranularPermission, Permission> = { "patient.view": "patients:read", "patient.create": "patients:write", "patient.update": "patients:write", "appointment.view": "appointments:read", "appointment.create": "appointments:write", "appointment.update": "appointments:write", "appointment.cancel": "appointments:write", "clinical.view": "clinical:read", "clinical.write": "clinical:write", "prescription.create": "prescriptions:write", "prescription.view": "clinical:read", "lab.order.create": "lab-requests:write", "lab.result.write": "lab-results:write", "lab.report.publish": "lab-reports:publish", "billing.create": "billing:write", "billing.payment.collect": "payments:write", "billing.refund.request": "payments:write", "bed.manage": "beds:write", "employee.manage": "employees:write", "leave.approve": "leave:approve", "pharmacy.dispense": "dispensing:write", "pharmacy.inventory.manage": "stock:write", "cms.manage": "settings:write", "user.manage": "users:write", "audit.view": "reports:read" };
export function can(user: { role: Role; permissions: Permission[] }, permission: GranularPermission) { return hasPermission(user.role, granularMap[permission], user.permissions); }
