import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requirePermission } from "@/lib/server-auth";
import { Counter } from "@/models/Counter";
import { Ambulance } from "@/models/Ambulance";
import { AmbulanceTrip } from "@/models/AmbulanceTrip";
const ambulanceSchema = z.object({ vehicleNumber: z.string().trim().min(4).max(40), driver: z.string().trim().max(120).optional(), phone: z.string().trim().max(30).optional(), type: z.enum(["basic", "advanced_life_support", "patient_transport", "neonatal"]).default("basic"), status: z.enum(["available", "maintenance"]).default("available") });
const tripSchema = z.object({ action: z.literal("trip"), ambulance: z.string().length(24), patient: z.string().length(24).optional(), pickup: z.string().trim().min(2).max(300), destination: z.string().trim().min(2).max(300) });
const updateSchema = z.object({ id: z.string().length(24), status: z.enum(["available", "maintenance"]).optional(), driver: z.string().trim().max(120).optional(), phone: z.string().trim().max(30).optional(), type: z.enum(["basic", "advanced_life_support", "patient_transport", "neonatal"]).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "ambulance:write"); const trips = request.nextUrl.searchParams.get("trips") === "true"; if (trips) return NextResponse.json(await AmbulanceTrip.find().populate("ambulance", "ambulanceId vehicleNumber status").populate("patient", "name uhid").sort({ createdAt: -1 }).limit(200).lean()); return NextResponse.json(await Ambulance.find().populate("currentPatient", "name uhid").sort({ vehicleNumber: 1 }).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load ambulances"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "ambulance:write"); const body = await request.json(); if (body?.action === "trip") { const input = tripSchema.parse(body); const ambulance = await Ambulance.findOneAndUpdate({ _id: input.ambulance, status: "available" }, { $set: { status: "assigned", currentPatient: input.patient } }, { new: true }); if (!ambulance) return NextResponse.json({ error: "Ambulance is unavailable" }, { status: 409 }); const trip = await AmbulanceTrip.create({ ...input, ambulance: ambulance._id, status: "assigned", assignedAt: new Date(), recordedBy: user.firebaseUid }); await audit(user.firebaseUid, "ambulance.assigned", "AmbulanceTrip", trip._id.toString(), { ambulance: ambulance.ambulanceId }); return NextResponse.json(trip, { status: 201 }); } const input = ambulanceSchema.parse(body); const counter = await Counter.findOneAndUpdate({ key: "ambulance" }, { $inc: { value: 1 } }, { upsert: true, new: true }); const ambulance = await Ambulance.create({ ...input, ambulanceId: `AMB-${String(counter.value).padStart(4, "0")}` }); await audit(user.firebaseUid, "ambulance.created", "Ambulance", ambulance._id.toString(), { ambulanceId: ambulance.ambulanceId }); return NextResponse.json(ambulance, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid ambulance details" : error instanceof Error ? error.message : "Unable to save ambulance"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
export async function PATCH(request: NextRequest) { try { const user = await requirePermission(request, "ambulance:write"); const body = await request.json(); if (body?.tripId) { const schema = z.object({ tripId: z.string().length(24), status: z.enum(["pickup", "on_trip", "hospital_arrival", "completed", "cancelled"]) }); const input = schema.parse(body); const timeKey = input.status === "pickup" ? "pickupAt" : input.status === "on_trip" ? "startedAt" : input.status === "hospital_arrival" ? "arrivedAt" : "endedAt"; const trip = await AmbulanceTrip.findByIdAndUpdate(input.tripId, { $set: { status: input.status, [timeKey]: new Date() } }, { new: true }); if (!trip) return NextResponse.json({ error: "Trip not found" }, { status: 404 }); const ambulanceStatus = input.status === "on_trip" ? "on_trip" : input.status === "hospital_arrival" ? "returning" : input.status === "completed" || input.status === "cancelled" ? "available" : "assigned"; await Ambulance.findByIdAndUpdate(trip.ambulance, { $set: { status: ambulanceStatus, currentPatient: ambulanceStatus === "available" ? undefined : trip.patient } }); await audit(user.firebaseUid, `ambulance.trip_${input.status}`, "AmbulanceTrip", input.tripId); return NextResponse.json(trip); } const input = updateSchema.parse(body); const { id, ...changes } = input; const ambulance = await Ambulance.findByIdAndUpdate(id, { $set: changes }, { new: true }); if (!ambulance) return NextResponse.json({ error: "Ambulance not found" }, { status: 404 }); await audit(user.firebaseUid, "ambulance.updated", "Ambulance", id); return NextResponse.json(ambulance); } catch (error) { const message = error instanceof z.ZodError ? "Invalid ambulance update" : error instanceof Error ? error.message : "Unable to update ambulance"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
