import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/server-auth";
import { Counter } from "@/models/Counter";
import { EmergencyCase } from "@/models/EmergencyCase";
import { assignAvailableBed } from "@/lib/bed-operations";
const schema = z.object({ patient: z.string().length(24), triage: z.enum(["critical", "very_urgent", "urgent", "stable"]), arrivalAt: z.coerce.date().optional(), bed: z.string().length(24).optional(), assignedStaff: z.array(z.string().length(24)).default([]), ambulance: z.string().max(100).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "emergency:write"); const status = request.nextUrl.searchParams.get("status"); const filter: Record<string, unknown> = {}; if (status) filter.status = status; return NextResponse.json(await EmergencyCase.find(filter).populate("patient", "name uhid").sort({ arrivalAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load emergency cases"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "emergency:write"); const input = schema.parse(await request.json()); const value = await Counter.findOneAndUpdate({ key: `emergency:${new Date().getFullYear()}` }, { $inc: { value: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); if (input.bed) await assignAvailableBed({ bedId: input.bed, patientId: input.patient, assignedBy: user.firebaseUid }); const emergency = await EmergencyCase.create({ ...input, caseNumber: `ER-${new Date().getFullYear()}-${String(value.value).padStart(6, "0")}`, arrivalAt: input.arrivalAt ?? new Date() }); return NextResponse.json(emergency, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid emergency case" : error instanceof Error ? error.message : "Unable to create emergency case"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 409 }); } }
