import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { connectToDatabase } from "@/lib/mongodb";
import { Appointment } from "@/models/Appointment";
import { DoctorSchedule } from "@/models/DoctorSchedule";
import { Counter } from "@/models/Counter";
import { limit } from "@/lib/security/rate-limit";
const schema = z.object({ patient: z.string().length(24), patientName: z.string().min(2), email: z.email(), phone: z.string().min(8), department: z.string().min(2), doctorUid: z.string().min(4), doctor: z.string().min(2), startAt: z.coerce.date(), payAtHospital: z.boolean().default(true), walkIn: z.boolean().default(false) });
export async function POST(request: NextRequest) { try { const limiter = limit(`booking:${request.headers.get("x-forwarded-for") ?? "local"}`, 12, 60_000); if (!limiter.allowed) return NextResponse.json({ error: "Too many booking attempts." }, { status: 429, headers: { "Retry-After": String(limiter.retryAfter) } }); const input = schema.parse(await request.json()); await connectToDatabase(); const schedule = await DoctorSchedule.findOne({ doctorUid: input.doctorUid }).lean(); if (!schedule) return NextResponse.json({ error: "Doctor schedule unavailable" }, { status: 400 }); const dayKey = input.startAt.toISOString().slice(0, 10); const start = new Date(input.startAt); const end = new Date(start.getTime() + schedule.consultationMinutes * 60000); const working = schedule.workingDays.includes(start.getDay()) && !schedule.leaveDates.includes(dayKey); const inRange = start >= new Date(`${dayKey}T${schedule.startTime}:00`) && end <= new Date(`${dayKey}T${schedule.endTime}:00`); const count = await Appointment.countDocuments({ doctorUid: input.doctorUid, startAt: { $gte: new Date(`${dayKey}T00:00:00`), $lt: new Date(`${dayKey}T23:59:59`) }, status: { $nin: ["cancelled", "no_show"] } }); if (!working || !inRange || count >= schedule.dailyLimit) return NextResponse.json({ error: "Selected slot is no longer available" }, { status: 409 }); const token = await Counter.findOneAndUpdate({ key: `token:${input.doctorUid}:${dayKey}` }, { $inc: { value: 1 } }, { upsert: true, new: true }); const appointment = await Appointment.create({ ...input, reference: `APT-${Date.now().toString(36).toUpperCase()}`, preferredDate: start, startAt: start, endAt: end, token: token.value, status: "confirmed" }); return NextResponse.json(appointment, { status: 201 }); } catch (error) { const code = typeof error === "object" && error && "code" in error ? (error as { code?: number }).code : undefined; return NextResponse.json({ error: code === 11000 ? "This slot was just booked. Choose another time." : "Unable to book appointment" }, { status: code === 11000 ? 409 : 400 }); } }
