import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requirePermission } from "@/lib/server-auth";
import { Medicine } from "@/models/Medicine";
import { MedicineBatch } from "@/models/MedicineBatch";
const medicineSchema = z.object({ name: z.string().trim().min(2).max(160), genericName: z.string().trim().max(160).optional(), brand: z.string().trim().max(160).optional(), category: z.string().trim().max(120).optional(), reorderLevel: z.number().int().min(0).default(0), active: z.boolean().default(true), batch: z.object({ batchNumber: z.string().trim().min(1).max(80), expiryDate: z.coerce.date(), quantity: z.number().int().positive(), purchasePrice: z.number().min(0).optional(), salePrice: z.number().min(0).optional(), supplier: z.string().trim().max(160).optional() }).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "pharmacy:read"); const q = request.nextUrl.searchParams.get("q")?.trim(); const medicineFilter = q ? { name: { $regex: q, $options: "i" } } : {}; const medicines = await Medicine.find(medicineFilter).sort({ name: 1 }).limit(100).lean(); const batches = await MedicineBatch.find({ medicine: { $in: medicines.map(medicine => medicine._id) }, quantity: { $gt: 0 }, expiryDate: { $gt: new Date() } }).sort({ expiryDate: 1 }).lean(); const batchesByMedicine = new Map<string, typeof batches>(); for (const batch of batches) { const key = batch.medicine.toString(); batchesByMedicine.set(key, [...(batchesByMedicine.get(key) ?? []), batch]); } return NextResponse.json(medicines.map(medicine => { const medicineBatches = batchesByMedicine.get(medicine._id.toString()) ?? []; const stock = medicineBatches.reduce((sum, batch) => sum + batch.quantity, 0); return { ...medicine, batches: medicineBatches, stock, lowStock: stock <= medicine.reorderLevel }; })); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load medicines"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "pharmacy:write"); const input = medicineSchema.parse(await request.json()); if (input.batch && input.batch.expiryDate <= new Date()) return NextResponse.json({ error: "A new batch must have a future expiry date" }, { status: 400 }); const medicine = await Medicine.create({ name: input.name, genericName: input.genericName, brand: input.brand, category: input.category, reorderLevel: input.reorderLevel, active: input.active }); if (input.batch) await MedicineBatch.create({ ...input.batch, medicine: medicine._id }); await audit(user.firebaseUid, "medicine.created", "Medicine", medicine._id.toString(), { batch: input.batch?.batchNumber }); return NextResponse.json(medicine, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid medicine" : error instanceof Error ? error.message : "Unable to create medicine"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
