import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/server-auth";
import { Counter } from "@/models/Counter";
import { Admission } from "@/models/Admission";
import { Visit } from "@/models/Visit";
import { assignAvailableBed } from "@/lib/bed-operations";
import { AuditLog } from "@/models/AuditLog";
const schema = z.object({ patient: z.string().length(24), source: z.enum(["opd", "emergency", "direct"]), doctorUid: z.string().optional(), ward: z.string().length(24).optional(), room: z.string().length(24).optional(), bed: z.string().length(24), reason: z.string().min(2), diagnosis: z.string().optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "admissions:write"); const status = request.nextUrl.searchParams.get("status"); const patient = request.nextUrl.searchParams.get("patient"); const filter: Record<string, unknown> = {}; if (status) filter.status = status; if (patient) filter.patient = patient; return NextResponse.json(await Admission.find(filter).populate("patient", "name uhid").populate("bed", "bedNumber").sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load admissions"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "admissions:write"); const input = schema.parse(await request.json()); await assignAvailableBed({ bedId: input.bed, patientId: input.patient, assignedBy: user.firebaseUid }); const year = new Date().getFullYear(); const counter = await Counter.findOneAndUpdate({ key: `admission:${year}` }, { $inc: { value: 1 } }, { upsert: true, new: true }); const admission = await Admission.create({ ...input, admissionNumber: `ADM-${year}-${String(counter.value).padStart(6, "0")}` }); const visitCounter = await Counter.findOneAndUpdate({ key: `ipd-visit:${year}` }, { $inc: { value: 1 } }, { upsert: true, new: true }); await Visit.create({ visitNumber: `IPD-${year}-${String(visitCounter.value).padStart(6, "0")}`, patient: input.patient, doctorUid: input.doctorUid, type: "ipd", status: "open", checkedInAt: new Date() }); await AuditLog.create({ actorUid: user.firebaseUid, action: "admission.created", entityType: "Admission", entityId: admission._id.toString(), after: admission.toObject() }); return NextResponse.json(admission, { status: 201 }); } catch (error) { const code = typeof error === "object" && error && "code" in error ? (error as { code?: number }).code : undefined; const message = error instanceof z.ZodError ? "Invalid admission" : error instanceof Error ? error.message : "Unable to admit patient"; return NextResponse.json({ error: code === 11000 ? "Patient already has an active admission" : message }, { status: code === 11000 ? 409 : message === "Forbidden" ? 403 : 400 }); } }
