import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/server-auth";
import { connectToDatabase } from "@/lib/mongodb";
import { MedicineBatch } from "@/models/MedicineBatch";
import { StockMovement } from "@/models/StockMovement";
import { Dispense } from "@/models/Dispense";
const schema = z.object({ patient: z.string().length(24), batch: z.string().length(24), quantity: z.number().int().positive(), prescription: z.string().length(24).optional(), billingReference: z.string().max(120).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "pharmacy:read"); const patient = request.nextUrl.searchParams.get("patient"); const filter: Record<string, unknown> = {}; if (patient) filter.patient = patient; return NextResponse.json(await Dispense.find(filter).populate("patient", "name uhid").populate({ path: "batch", populate: { path: "medicine", select: "name" } }).sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load dispense history"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "dispensing:write"); const input = schema.parse(await request.json()); const db = await connectToDatabase(); const session = await db.startSession(); let dispense; try { await session.withTransaction(async () => { const batch = await MedicineBatch.findOneAndUpdate({ _id: input.batch, quantity: { $gte: input.quantity }, expiryDate: { $gt: new Date() } }, { $inc: { quantity: -input.quantity } }, { new: true, session }); if (!batch) throw new Error("Insufficient stock, expired batch, or unknown batch"); dispense = (await Dispense.create([{ ...input, dispensedBy: user.firebaseUid }], { session }))[0]; await StockMovement.create([{ batch: batch._id, medicine: batch.medicine, type: "dispense", quantity: -input.quantity, reference: input.billingReference, performedBy: user.firebaseUid }], { session }); }); } finally { await session.endSession(); } return NextResponse.json(dispense, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid dispense request" : error instanceof Error ? error.message : "Unable to dispense medicine"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 409 }); } }
