import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/server-auth";
import { audit } from "@/lib/audit";
import { Counter } from "@/models/Counter";
import { Invoice } from "@/models/Invoice";
const schema = z.object({ patient: z.string().length(24), category: z.enum(["consultation", "opd", "ipd", "laboratory", "pharmacy", "procedure", "room", "surgery", "health_package"]), lines: z.array(z.object({ description: z.string().min(1).max(200), quantity: z.number().positive(), unitPrice: z.number().min(0) })).min(1), discount: z.number().min(0).default(0), tax: z.number().min(0).default(0) });
export async function GET(request: NextRequest) { try { await requirePermission(request, "billing:read"); const patient = request.nextUrl.searchParams.get("patient"); const status = request.nextUrl.searchParams.get("status"); const filter: Record<string, unknown> = {}; if (patient) filter.patient = patient; if (status) filter.status = status; return NextResponse.json(await Invoice.find(filter).populate("patient", "name uhid").sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load invoices"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "billing:write"); const input = schema.parse(await request.json()); const subtotal = input.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0); const total = Math.max(0, subtotal - input.discount + input.tax); const value = await Counter.findOneAndUpdate({ key: `invoice:${new Date().getFullYear()}` }, { $inc: { value: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); const invoice = await Invoice.create({ ...input, invoiceNumber: `INV-${new Date().getFullYear()}-${String(value.value).padStart(6, "0")}`, lines: input.lines.map(line => ({ ...line, amount: line.quantity * line.unitPrice })), subtotal, total, due: total }); await audit(user.firebaseUid, "invoice.created", "Invoice", invoice._id.toString(), { invoiceNumber: invoice.invoiceNumber, patient: input.patient, total: invoice.total });
    return NextResponse.json(invoice, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid invoice" : error instanceof Error ? error.message : "Unable to create invoice"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
