import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/server-auth";
import { InventoryItem } from "@/models/InventoryItem";
import { InventoryMovement } from "@/models/InventoryMovement";
import { connectToDatabase } from "@/lib/mongodb";
const schema = z.object({ item: z.string().length(24), type: z.enum(["purchase", "stock_in", "stock_out", "allocation", "adjustment"]), quantity: z.number().positive(), department: z.string().optional(), supplier: z.string().optional(), note: z.string().max(500).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "inventory:read"); const item = request.nextUrl.searchParams.get("item"); const filter: Record<string, unknown> = {}; if (item) filter.item = item; return NextResponse.json(await InventoryMovement.find(filter).populate("item", "name unit").sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load inventory movements"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "inventory:write"); const input = schema.parse(await request.json()); const db = await connectToDatabase(); const session = await db.startSession(); let movement; try { await session.withTransaction(async () => { const decrement = input.type === "stock_out" || input.type === "allocation"; const item = await InventoryItem.findOneAndUpdate(decrement ? { _id: input.item, quantity: { $gte: input.quantity } } : { _id: input.item }, { $inc: { quantity: decrement ? -input.quantity : input.quantity } }, { new: true, session }); if (!item) throw new Error("Item not found or insufficient stock"); movement = (await InventoryMovement.create([{ ...input, performedBy: user.firebaseUid, quantity: decrement ? -input.quantity : input.quantity }], { session }))[0]; }); } finally { await session.endSession(); } return NextResponse.json(movement, { status: 201 }); } catch (error) { const message = error instanceof Error ? error.message : "Unable to move stock"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 409 }); } }
