import { Ambulance, ArrowRight, CalendarDays, Clock3, MapPin, Phone } from "lucide-react";
import Link from "next/link";
import { PageShell } from "@/components/public/page-shell";
import { Reveal } from "@/components/public/reveal";

export const metadata = { title: "Contact Us | Health Care .Pvt .Ltd" };

const contactOptions = [
  { icon: CalendarDays, title: "Appointments and enquiries", text: "Speak with our care team for appointments, directions and general hospital information.", action: "+91 33 4000 2000", href: "tel:+913340002000" },
  { icon: Ambulance, title: "Emergency care", text: "If you need urgent medical assistance, our emergency service is available around the clock.", action: "Call emergency care", href: "tel:+913340002000" },
  { icon: MapPin, title: "Visit the hospital", text: "12 Wellness Avenue, Kolkata 700001. Our team can help you plan your visit.", action: "Get directions", href: "https://maps.google.com/?q=12+Wellness+Avenue+Kolkata+700001" },
];

export default function Contact() {
  return <PageShell><main className="bg-canvas"><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><Reveal><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Contact us</p><h1 className="mt-4 max-w-2xl font-display text-4xl font-semibold leading-tight text-ink sm:text-5xl">We’re here to help you find the right care.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-ink-muted">Whether you are planning an appointment, visiting someone or need to find a specialist, our care team is ready to guide you.</p></Reveal><div className="mt-12 grid gap-6 lg:grid-cols-3">{contactOptions.map(({ icon: Icon, title, text, action, href }, index) => <Reveal key={title} delay={index * .07}><article className="flex h-full flex-col rounded-[1.5rem] border border-line bg-white p-7 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-brand-soft text-brand"><Icon size={24} /></span><h2 className="mt-6 font-display text-2xl font-semibold text-ink">{title}</h2><p className="mt-3 flex-1 leading-7 text-ink-muted">{text}</p><a href={href} target={href.startsWith("https") ? "_blank" : undefined} rel={href.startsWith("https") ? "noreferrer" : undefined} className="mt-7 inline-flex items-center gap-2 font-bold text-brand transition hover:gap-3 hover:text-brand-strong">{action}<ArrowRight size={17} /></a></article></Reveal>)}</div><Reveal><div className="mt-12 grid gap-6 rounded-[2rem] bg-brand-strong p-8 text-white sm:grid-cols-[auto_1fr] sm:items-center lg:p-10"><span className="grid size-14 place-items-center rounded-2xl bg-white/10 text-brand-bright"><Clock3 size={27} /></span><div><h2 className="font-display text-2xl font-semibold">Open whenever you need us.</h2><p className="mt-2 max-w-2xl leading-7 text-white/75">Our emergency care service is available 24/7. For routine appointments, call our team and we’ll help find a convenient time.</p></div></div></Reveal><div className="mt-8 flex flex-wrap items-center gap-3 text-sm font-medium text-ink-muted"><Phone size={18} className="text-brand" /><span>General enquiries:</span><a className="font-bold text-brand hover:text-brand-strong" href="tel:+913340002000">+91 33 4000 2000</a><span className="hidden text-line sm:inline">•</span><Link href="/appointments" className="font-bold text-brand hover:text-brand-strong">Book online</Link></div></section></main></PageShell>;
}
