import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requirePermission } from "@/lib/server-auth";
import { Counter } from "@/models/Counter";
import { BloodDonor } from "@/models/BloodDonor";
import { BloodStock } from "@/models/BloodStock";
import { BloodUnit } from "@/models/BloodUnit";
const groups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"] as const;
const schema = z.object({ donor: z.string().length(24).optional(), bloodGroup: z.enum(groups), collectedAt: z.coerce.date(), expiresAt: z.coerce.date(), storage: z.string().trim().max(120).optional(), screening: z.enum(["cleared", "pending", "failed"]).default("cleared") });
export async function GET(request: NextRequest) { try { await requirePermission(request, "blood-bank:write"); await BloodUnit.updateMany({ expiresAt: { $lte: new Date() }, status: { $in: ["available", "reserved"] } }, { $set: { status: "expired" } }); const [units, stock] = await Promise.all([BloodUnit.find().populate("donor", "name bloodGroup").populate("issue.patient", "name uhid").sort({ expiresAt: 1 }).lean(), BloodStock.find().sort({ bloodGroup: 1 }).lean()]); return NextResponse.json({ units, stock }); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load blood inventory"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "blood-bank:write"); const input = schema.parse(await request.json()); if (input.expiresAt <= input.collectedAt) return NextResponse.json({ error: "Expiry date must be later than collection date" }, { status: 400 }); const donor = input.donor ? await BloodDonor.findById(input.donor) : null; if (input.donor && (!donor || !donor.eligible)) return NextResponse.json({ error: "Donor is not eligible" }, { status: 409 }); const counter = await Counter.findOneAndUpdate({ key: "blood_unit" }, { $inc: { value: 1 } }, { upsert: true, new: true }); const status = input.screening === "cleared" ? "available" : input.screening === "failed" ? "discarded" : "reserved"; const unit = await BloodUnit.create({ ...input, unitNumber: `BB-${String(counter.value).padStart(7, "0")}`, status }); if (status === "available") await BloodStock.findOneAndUpdate({ bloodGroup: input.bloodGroup }, { $inc: { availableUnits: 1 }, $set: { updatedBy: user.firebaseUid } }, { upsert: true }); if (status === "reserved") await BloodStock.findOneAndUpdate({ bloodGroup: input.bloodGroup }, { $inc: { reservedUnits: 1 }, $set: { updatedBy: user.firebaseUid } }, { upsert: true }); if (donor) { donor.lastDonatedAt = input.collectedAt; await donor.save(); } await audit(user.firebaseUid, "blood.collected", "BloodUnit", unit._id.toString(), { bloodGroup: input.bloodGroup, status }); return NextResponse.json(unit, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid blood unit" : error instanceof Error ? error.message : "Unable to collect blood"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
