import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { createFirebaseUser, deleteFirebaseUser } from "@/lib/firebase-admin";
import { PERMISSIONS, ROLES, type Permission } from "@/lib/roles";
import { getRequestUser, requirePermission } from "@/lib/server-auth";
import { EmployeeProfile } from "@/models/EmployeeProfile";
import { Patient } from "@/models/Patient";
import { User } from "@/models/User";
const id = z.string().regex(/^[a-f\d]{24}$/i);
const schema = z.object({ name: z.string().trim().min(2).max(120), email: z.email(), temporaryPassword: z.string().min(6).max(128), role: z.enum(ROLES), department: z.string().trim().max(120).optional(), employee: id.optional(), patient: id.optional(), permissions: z.array(z.string()).refine((values) => values.every((value) => PERMISSIONS.includes(value as Permission)), "Invalid permission").default([]), permissionMode: z.enum(["role_default", "custom"]).default("role_default") }).refine((value) => !(value.employee && value.patient), "An account can link to an employee or patient, not both").refine((value) => value.role === "patient" ? Boolean(value.patient) : !value.patient, "Patient accounts must link to a patient profile");
async function requireAdmin(request: NextRequest) { const actor = await getRequestUser(request); if (actor.role !== "admin") throw new Error("Forbidden"); return actor; }
export async function GET(request: NextRequest) { try { await requirePermission(request, "users:read"); return NextResponse.json(await User.find().select("name email role active status department patient profile firebaseUid lastLoginAt createdAt permissions permissionMode").populate("patient", "name uhid").populate("profile", "staffId designation").sort({ name: 1 }).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load users"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { let firebaseUid: string | undefined; try { const actor = await requireAdmin(request); const input = schema.parse(await request.json()); if (await User.exists({ email: input.email.toLowerCase() })) return NextResponse.json({ error: "A hospital account already uses this email" }, { status: 409 }); if (input.employee && !await EmployeeProfile.exists({ _id: input.employee })) return NextResponse.json({ error: "Employee profile not found" }, { status: 404 }); if (input.patient && !await Patient.exists({ _id: input.patient })) return NextResponse.json({ error: "Patient profile not found" }, { status: 404 }); const firebase = await createFirebaseUser({ email: input.email.toLowerCase(), password: input.temporaryPassword, displayName: input.name }); firebaseUid = firebase.uid; const account = await User.create({ firebaseUid, name: input.name, email: input.email.toLowerCase(), role: input.role, department: input.department, profile: input.employee, patient: input.patient, permissions: input.permissions, permissionMode: input.permissionMode, active: true, status: "active" }); if (input.employee) await EmployeeProfile.findByIdAndUpdate(input.employee, { $set: { user: account._id } }); await audit(actor.firebaseUid, "user.created", "User", account._id.toString(), { role: input.role, employee: input.employee, patient: input.patient }); return NextResponse.json(account, { status: 201 }); } catch (error) { if (firebaseUid) await deleteFirebaseUser(firebaseUid).catch(() => undefined); const message = error instanceof z.ZodError ? error.issues[0]?.message ?? "Invalid user" : error instanceof Error ? error.message : "Unable to create user"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
