"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

const schema = z.object({ patientName: z.string().min(2, "Please enter your name"), email: z.email("Enter a valid email"), phone: z.string().min(8, "Enter a valid phone number"), department: z.string().min(1, "Select a department"), doctor: z.string().optional(), preferredDate: z.string().min(1, "Choose a preferred date"), message: z.string().max(1000).optional() });
type FormData = z.infer<typeof schema>;
const departments = ["Cardiology", "General Medicine", "Neurology", "Orthopaedics", "Paediatrics", "Women’s Health"];

export function AppointmentForm() {
  const [result, setResult] = useState<string>();
  const { register, handleSubmit, formState: { errors, isSubmitting }, reset } = useForm<FormData>({ resolver: zodResolver(schema) });
  const onSubmit = async (data: FormData) => { setResult(undefined); try { const response = await fetch("/api/appointments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setResult(`Your request is in. Reference: ${payload.reference}`); reset(); } catch { setResult("We could not send your request. Please call +91 33 4000 2000."); } };
  const field = "mt-1 w-full rounded-xl border border-line bg-white px-4 py-3 text-ink outline-none transition placeholder:text-ink-subtle focus:border-brand-bright focus:ring-4 focus:ring-brand-bright/15";
  return <form onSubmit={handleSubmit(onSubmit)} className="grid gap-5 rounded-3xl bg-white p-6 shadow-xl shadow-ink/5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-ink">Full name<input {...register("patientName")} className={field} placeholder="Your name" />{errors.patientName && <span className="text-xs text-rose-600">{errors.patientName.message}</span>}</label><label className="text-sm font-semibold text-ink">Phone<input {...register("phone")} className={field} placeholder="+91 …" />{errors.phone && <span className="text-xs text-rose-600">{errors.phone.message}</span>}</label></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-ink">Email<input {...register("email")} className={field} placeholder="you@example.com" />{errors.email && <span className="text-xs text-rose-600">{errors.email.message}</span>}</label><label className="text-sm font-semibold text-ink">Department<select {...register("department")} className={field}><option value="">Select a department</option>{departments.map((d) => <option key={d}>{d}</option>)}</select>{errors.department && <span className="text-xs text-rose-600">{errors.department.message}</span>}</label></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-ink">Preferred date<input type="date" min={new Date().toISOString().split("T")[0]} {...register("preferredDate")} className={field} />{errors.preferredDate && <span className="text-xs text-rose-600">{errors.preferredDate.message}</span>}</label><label className="text-sm font-semibold text-ink">Preferred doctor (optional)<input {...register("doctor")} className={field} placeholder="Doctor’s name" /></label></div><label className="text-sm font-semibold text-ink">How can we help?<textarea {...register("message")} className={`${field} min-h-24`} placeholder="Briefly describe your concern (optional)" /></label><button disabled={isSubmitting} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-6 py-3.5 font-semibold text-white transition hover:bg-brand-strong disabled:opacity-60">{isSubmitting && <LoaderCircle className="animate-spin" size={18} />}Request appointment</button>{result && <p className="flex items-center gap-2 rounded-xl bg-brand-soft p-3 text-sm font-semibold text-brand-strong"><CheckCircle2 size={18} />{result}</p>}</form>;
}
