import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getRequestUser, requirePermission } from "@/lib/server-auth";
import { hasPermission } from "@/lib/roles";
import { Prescription } from "@/models/Prescription";
import { AuditLog } from "@/models/AuditLog";
const schema = z.object({ patient: z.string().length(24), visit: z.string().length(24).optional(), diagnosis: z.string().max(1000).optional(), medicines: z.array(z.object({ medicine: z.string().length(24).optional(), name: z.string().min(2), dosage: z.string().min(1), frequency: z.string().min(1), duration: z.string().min(1), instructions: z.string().max(500).optional() })).min(1), followUpDate: z.coerce.date().optional(), notes: z.string().max(3000).optional(), finalize: z.boolean().default(false) });
export async function GET(request: NextRequest) { try { const user = await getRequestUser(request); if (!hasPermission(user.role, "clinical:read", user.permissions) && !hasPermission(user.role, "pharmacy:read", user.permissions)) throw new Error("Forbidden"); const patient = request.nextUrl.searchParams.get("patient"); const status = request.nextUrl.searchParams.get("status"); const filter: Record<string, unknown> = {}; if (patient) filter.patient = patient; if (status) filter.status = status; if (user.role === "doctor") filter.doctorUid = user.firebaseUid; return NextResponse.json(await Prescription.find(filter).populate("patient", "name uhid").sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load prescriptions"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "prescriptions:write"); const input = schema.parse(await request.json()); const prescription = await Prescription.create({ ...input, doctorUid: user.firebaseUid, status: input.finalize ? "finalized" : "draft", finalizedAt: input.finalize ? new Date() : undefined }); await AuditLog.create({ actorUid: user.firebaseUid, action: "prescription.created", entityType: "Prescription", entityId: prescription._id.toString(), after: prescription.toObject() }); return NextResponse.json(prescription, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid prescription" : error instanceof Error ? error.message : "Unable to create prescription"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
