import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { connectToDatabase } from "@/lib/mongodb";
import { requirePermission } from "@/lib/server-auth";
import { limit } from "@/lib/security/rate-limit";
import { Counter } from "@/models/Counter";
import { Patient } from "@/models/Patient";
const documentSchema = z.object({ name: z.string().trim().min(1).max(180), type: z.string().trim().max(100), data: z.string().max(7_000_000).refine((value) => /^data:(application\/pdf|image\/(png|jpeg|webp));base64,[a-z0-9+/=]+$/i.test(value), "Document must be a PDF, PNG, JPEG, or WebP file."), uploadedAt: z.coerce.date().optional() });
export const patientSchema = z.object({ name: z.string().trim().min(2).max(120), phone: z.string().trim().min(8).max(30), email: z.email().optional().or(z.literal("")), dateOfBirth: z.coerce.date().optional(), gender: z.enum(["female", "male", "other", "prefer_not_to_say"]).optional(), address: z.string().trim().max(500).optional().or(z.literal("")), emergencyContact: z.object({ name: z.string().trim().max(120).optional().or(z.literal("")), phone: z.string().trim().max(30).optional().or(z.literal("")), relation: z.string().trim().max(80).optional().or(z.literal("")) }).optional(), allergies: z.array(z.string().trim().min(1).max(100)).max(50).optional().default([]), medicalHistory: z.string().trim().max(5000).optional().or(z.literal("")), documents: z.array(documentSchema).max(12).optional().default([]) });
async function nextUhid() { const year = new Date().getFullYear(); const counter = await Counter.findOneAndUpdate({ key: `uhid:${year}` }, { $inc: { value: 1 } }, { new: true, upsert: true, setDefaultsOnInsert: true }); return `HSP-${year}-${String(counter.value).padStart(6, "0")}`; }
function escapeRegex(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
export async function GET(request: NextRequest) { try { await requirePermission(request, "patients:read"); const q = request.nextUrl.searchParams.get("q")?.trim(); const expression = q ? new RegExp(escapeRegex(q), "i") : undefined; const filter = expression ? { $or: [{ name: expression }, { uhid: expression }, { phone: expression }, { email: expression }] } : {}; return NextResponse.json(await Patient.find(filter).select("name uhid patientId phone email dateOfBirth gender active createdAt").sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load patients"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const actor = await requirePermission(request, "patients:write"); const limiter = limit(`patient-create:${actor.firebaseUid}`, 30, 60_000); if (!limiter.allowed) return NextResponse.json({ error: "Too many registrations. Please slow down." }, { status: 429, headers: { "Retry-After": String(limiter.retryAfter) } }); await connectToDatabase(); const input = patientSchema.parse(await request.json()); const matchingPatient = await Patient.findOne({ name: new RegExp(`^${escapeRegex(input.name)}$`, "i"), phone: input.phone }).select("_id name uhid").lean(); if (matchingPatient) return NextResponse.json({ error: `A patient profile already exists for this name and phone number (UHID ${matchingPatient.uhid}). Open that profile instead of creating another UHID.`, patient: matchingPatient }, { status: 409 }); for (let attempt = 0; attempt < 3; attempt += 1) { const uhid = await nextUhid(); try { const patient = await Patient.create({ ...input, email: input.email || undefined, address: input.address || undefined, medicalHistory: input.medicalHistory || undefined, uhid, patientId: uhid }); return NextResponse.json(patient, { status: 201 }); } catch (error) { if (!(error instanceof Error) || !("code" in error) || (error as { code?: number }).code !== 11000) throw error; } } throw new Error("UHID allocation conflict"); } catch (error) { const message = error instanceof z.ZodError ? "Invalid patient details" : error instanceof Error ? error.message : "Unable to register patient"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
