import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { connectToDatabase } from "@/lib/mongodb";
import { requirePermission } from "@/lib/server-auth";
import { limit } from "@/lib/security/rate-limit";
import { Counter } from "@/models/Counter";
import { Patient } from "@/models/Patient";
const patientSchema = z.object({ name: z.string().min(2).max(120), phone: z.string().min(8).max(30), email: z.email().optional().or(z.literal("")), dateOfBirth: z.coerce.date().optional(), gender: z.enum(["female", "male", "other", "prefer_not_to_say"]).optional(), address: z.string().max(500).optional() });
async function nextUhid() { const year = new Date().getFullYear(); const counter = await Counter.findOneAndUpdate({ key: `uhid:${year}` }, { $inc: { value: 1 } }, { new: true, upsert: true, setDefaultsOnInsert: true }); return `HSP-${year}-${String(counter.value).padStart(6, "0")}`; }
export async function GET(request: NextRequest) { try { await requirePermission(request, "patients:read"); const q = request.nextUrl.searchParams.get("q")?.trim(); const filter = q ? { $or: [{ name: { $regex: q, $options: "i" } }, { uhid: { $regex: q, $options: "i" } }, { phone: { $regex: q, $options: "i" } }] } : {}; return NextResponse.json(await Patient.find(filter).sort({ createdAt: -1 }).limit(50).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load patients"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const actor = await requirePermission(request, "patients:write"); const limiter = limit(`patient-create:${actor.firebaseUid}`, 30, 60_000); if (!limiter.allowed) return NextResponse.json({ error: "Too many registrations. Please slow down." }, { status: 429, headers: { "Retry-After": String(limiter.retryAfter) } }); await connectToDatabase(); const input = patientSchema.parse(await request.json()); for (let attempt = 0; attempt < 3; attempt += 1) { const uhid = await nextUhid(); try { const patient = await Patient.create({ ...input, email: input.email || undefined, uhid, patientId: uhid }); return NextResponse.json(patient, { status: 201 }); } catch (error) { if (!(error instanceof Error) || !("code" in error) || (error as { code?: number }).code !== 11000) throw error; } } throw new Error("UHID allocation conflict"); } catch (error) { const message = error instanceof z.ZodError ? "Invalid patient details" : error instanceof Error ? error.message : "Unable to register patient"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
