import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requirePermission } from "@/lib/server-auth";
import { CmsContent } from "@/models/CmsContent";
const types = ["homepage_banner", "homepage_section", "about", "doctor", "department", "service", "facility", "package", "gallery", "blog", "faq", "testimonial", "contact", "social", "footer", "seo"] as const;
const schema = z.object({ key: z.string().trim().regex(/^[a-z0-9._-]{2,120}$/i), type: z.enum(types), title: z.string().trim().max(200).optional(), slug: z.string().trim().max(180).optional(), payload: z.unknown(), status: z.enum(["draft", "published", "archived"]).default("draft"), seo: z.object({ title: z.string().trim().max(160).optional(), description: z.string().trim().max(320).optional(), image: z.url().optional() }).optional() });
export async function GET(request: NextRequest) { const publicOnly = request.nextUrl.searchParams.get("public") === "1"; try { if (!publicOnly) await requirePermission(request, "settings:write"); const type = request.nextUrl.searchParams.get("type"); const key = request.nextUrl.searchParams.get("key"); const filter: Record<string, unknown> = publicOnly ? { status: "published", published: true } : {}; if (type) filter.type = type; if (key) filter.key = key; return NextResponse.json(await CmsContent.find(filter).sort({ createdAt: -1 }).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load CMS content"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function PUT(request: NextRequest) { try { const user = await requirePermission(request, "settings:write"); const input = schema.parse(await request.json()); const published = input.status === "published"; const previous = await CmsContent.findOne({ key: input.key }).lean(); const content = await CmsContent.findOneAndUpdate({ key: input.key }, { $set: { ...input, published } }, { upsert: true, new: true, setDefaultsOnInsert: true, runValidators: true }); await audit(user.firebaseUid, "cms.updated", "CmsContent", content._id.toString(), { key: input.key, type: input.type, status: input.status, beforeStatus: previous?.status }); return NextResponse.json(content); } catch (error) { const message = error instanceof z.ZodError ? "Invalid CMS content" : error instanceof Error ? error.message : "Unable to save content"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
export async function DELETE(request: NextRequest) { try { const user = await requirePermission(request, "settings:write"); const key = request.nextUrl.searchParams.get("key"); if (!key) return NextResponse.json({ error: "Content key is required" }, { status: 400 }); const content = await CmsContent.findOneAndUpdate({ key }, { $set: { status: "archived", published: false } }, { new: true }); if (!content) return NextResponse.json({ error: "Content not found" }, { status: 404 }); await audit(user.firebaseUid, "cms.archived", "CmsContent", content._id.toString(), { key }); return NextResponse.json(content); } catch (error) { const message = error instanceof Error ? error.message : "Unable to archive content"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
