import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requirePermission } from "@/lib/server-auth";
import { OperationTheatre } from "@/models/OperationTheatre";
import { Surgery } from "@/models/Surgery";
const surgerySchema = z.object({ theatre: z.string().length(24), patient: z.string().length(24), surgeonUid: z.string().min(4), assistants: z.array(z.string()).default([]), anesthetist: z.string().trim().max(120).optional(), procedure: z.string().trim().min(2).max(500), startAt: z.coerce.date(), endAt: z.coerce.date(), preOpChecklist: z.array(z.object({ item: z.string().trim().min(1), complete: z.boolean() })).default([]) });
const updateSchema = z.object({ id: z.string().length(24), status: z.enum(["scheduled", "preparing", "in_progress", "completed", "cancelled"]).optional(), operationNotes: z.string().trim().max(10_000).optional(), postOpNotes: z.string().trim().max(10_000).optional(), preOpChecklist: z.array(z.object({ item: z.string(), complete: z.boolean() })).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "surgery:write"); const theatres = request.nextUrl.searchParams.get("theatres") === "true"; if (theatres) return NextResponse.json(await OperationTheatre.find().sort({ name: 1 }).lean()); return NextResponse.json(await Surgery.find().populate("theatre", "name").populate("patient", "name uhid").sort({ startAt: 1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load surgeries"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "surgery:write"); const body = await request.json(); if (body?.action === "theatre") { const input = z.object({ name: z.string().trim().min(2).max(100) }).parse(body); const theatre = await OperationTheatre.create({ name: input.name }); await audit(user.firebaseUid, "ot.created", "OperationTheatre", theatre._id.toString()); return NextResponse.json(theatre, { status: 201 }); } const input = surgerySchema.parse(body); if (user.role === "doctor" && input.surgeonUid !== user.firebaseUid) return NextResponse.json({ error: "Doctors can schedule only their own surgeries" }, { status: 403 }); if (input.endAt <= input.startAt) return NextResponse.json({ error: "End time must follow start time" }, { status: 400 }); if (!await OperationTheatre.exists({ _id: input.theatre, active: true })) return NextResponse.json({ error: "Operation theatre is unavailable" }, { status: 409 }); const overlap = await Surgery.exists({ theatre: input.theatre, status: { $nin: ["cancelled", "completed"] }, startAt: { $lt: input.endAt }, endAt: { $gt: input.startAt } }); if (overlap) return NextResponse.json({ error: "Operation theatre is already booked for this time" }, { status: 409 }); const surgery = await Surgery.create(input); await audit(user.firebaseUid, "surgery.scheduled", "Surgery", surgery._id.toString()); return NextResponse.json(surgery, { status: 201 }); } catch (error) { const code = typeof error === "object" && error && "code" in error ? (error as { code?: number }).code : undefined; const message = error instanceof z.ZodError ? "Invalid surgery" : error instanceof Error ? error.message : "Unable to schedule surgery"; return NextResponse.json({ error: code === 11000 ? "Operation theatre is already booked for this time" : message }, { status: code === 11000 ? 409 : message === "Forbidden" ? 403 : 400 }); } }
export async function PATCH(request: NextRequest) { try { const user = await requirePermission(request, "surgery:write"); const { id, ...changes } = updateSchema.parse(await request.json()); const surgery = await Surgery.findByIdAndUpdate(id, { $set: changes }, { new: true, runValidators: true }); if (!surgery) return NextResponse.json({ error: "Surgery not found" }, { status: 404 }); await audit(user.firebaseUid, "surgery.updated", "Surgery", id, { fields: Object.keys(changes) }); return NextResponse.json(surgery); } catch (error) { const message = error instanceof z.ZodError ? "Invalid surgery update" : error instanceof Error ? error.message : "Unable to update surgery"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
