import { NextRequest, NextResponse } from "next/server";
import { requirePermission } from "@/lib/server-auth";
import { Appointment } from "@/models/Appointment";
import { Admission } from "@/models/Admission";
import { Bed } from "@/models/Bed";
import { Invoice } from "@/models/Invoice";
import { LabOrder } from "@/models/LabOrder";
import { Dispense } from "@/models/Dispense";
export async function GET(request: NextRequest) { try { await requirePermission(request, "reports:read"); const range = request.nextUrl.searchParams.get("range") ?? "today"; const end = new Date(); const start = new Date(end); if (range === "7d") start.setDate(end.getDate() - 7); else if (range === "30d") start.setDate(end.getDate() - 30); else if (range !== "custom") start.setHours(0, 0, 0, 0); const from = range === "custom" && request.nextUrl.searchParams.get("from") ? new Date(request.nextUrl.searchParams.get("from")!) : start; const to = range === "custom" && request.nextUrl.searchParams.get("to") ? new Date(request.nextUrl.searchParams.get("to")!) : end; const [appointments, waiting, admissions, discharges, occupancy, revenue, outstanding, labActivity, pharmacySales] = await Promise.all([Appointment.countDocuments({ createdAt: { $gte: from, $lte: to } }), Appointment.countDocuments({ status: "waiting" }), Admission.countDocuments({ status: "admitted" }), Admission.countDocuments({ status: "discharged", dischargedAt: { $gte: from, $lte: to } }), Bed.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]), Invoice.aggregate([{ $match: { createdAt: { $gte: from, $lte: to } } }, { $group: { _id: null, total: { $sum: "$paid" }, outstanding: { $sum: "$due" } } }]), Invoice.aggregate([{ $group: { _id: null, total: { $sum: "$due" } } }]), LabOrder.countDocuments({ createdAt: { $gte: from, $lte: to } }), Dispense.countDocuments({ createdAt: { $gte: from, $lte: to } })]); return NextResponse.json({ range, from, to, todayPatients: appointments, appointments, waiting, admissions, discharges, bedOccupancy: occupancy, revenue: revenue[0]?.total ?? 0, outstanding: outstanding[0]?.total ?? 0, labActivity, pharmacySales }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load analytics" }, { status: 401 }); } }
