import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/server-auth";
import { audit } from "@/lib/audit";
import { limit } from "@/lib/security/rate-limit";
import { Invoice } from "@/models/Invoice";
import { PaymentTransaction } from "@/models/PaymentTransaction";
import { refreshInvoiceStatus } from "@/lib/billing";
const schema = z.object({ invoice: z.string().length(24), type: z.enum(["payment", "advance", "refund", "adjustment"]), method: z.enum(["cash", "card", "upi", "online", "insurance"]), amount: z.number().positive(), reference: z.string().max(120).optional(), note: z.string().max(500).optional() });
export async function GET(request: NextRequest) { try { await requirePermission(request, "billing:read"); const invoice = request.nextUrl.searchParams.get("invoice"); const filter: Record<string, unknown> = {}; if (invoice) filter.invoice = invoice; return NextResponse.json(await PaymentTransaction.find(filter).populate("patient", "name uhid").sort({ createdAt: -1 }).limit(100).lean()); } catch (error) { const message = error instanceof Error ? error.message : "Unable to load payments"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 401 }); } }
export async function POST(request: NextRequest) { try { const user = await requirePermission(request, "payments:write"); const limiter = limit(`payment:${user.firebaseUid}`, 40, 60_000); if (!limiter.allowed) return NextResponse.json({ error: "Too many payment attempts. Please slow down." }, { status: 429, headers: { "Retry-After": String(limiter.retryAfter) } }); const input = schema.parse(await request.json()); const invoice = await Invoice.findById(input.invoice); if (!invoice) return NextResponse.json({ error: "Invoice not found" }, { status: 404 }); const transaction = await PaymentTransaction.create({ ...input, patient: invoice.patient, receivedBy: user.firebaseUid }); const balance = await refreshInvoiceStatus(invoice._id); await audit(user.firebaseUid, input.type === "refund" ? "payment.refunded" : "payment.collected", "PaymentTransaction", transaction._id.toString(), { invoice: input.invoice, amount: input.amount, method: input.method, type: input.type });
    return NextResponse.json({ transaction, balance: { paid: balance.paid, outstanding: balance.outstanding, status: balance.invoice.status } }, { status: 201 }); } catch (error) { const message = error instanceof z.ZodError ? "Invalid payment record" : error instanceof Error ? error.message : "Unable to collect payment"; return NextResponse.json({ error: message }, { status: message === "Forbidden" ? 403 : 400 }); } }
